#!/usr/bin/python

from uuid import uuid1
from optparse import OptionParser
import sys

parser = OptionParser()
parser.add_option("-x", action="store_const", const="hex", dest="format", default="hex", help="Display as hex")
parser.add_option("-i", action="store_const", const="int", dest="format", help="Display as integers")
parser.add_option("-b", action="store_true", dest="bare", help="Bare output, no dashes")
parser.add_option("-n", action="store", dest="count", type="int", default="1", help="Number of uuids to generate (default: 1)")
(options, uids) = parser.parse_args()

for i in range(0, options.count):
	uid = uuid1()
	if (options.format == "int"):
		print uid.int
	else:
		if (options.bare):
			print uid.hex
		else:
			# uid.hex does not output a dashed version, but converting to a string does
			print str(uid)
